language: node_js

node_js:
- "8"

cache:
  directories:
  - "node_modules"
  - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "sanguino-github"
    token:
      secure: "$SONAR_TOKEN"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
- npm run standard
- npm test
- sonar-scanner